version: '3.8'
services:

  jenkins:
    build: ./jenkins
    image: "docker.io/craigtho/azure-jenkins:latest"
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080/tcp"
      - "50000:50000/tcp"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home: